import React from 'react';

export const metadata = {
    title: 'Artesania',
    description: 'Generated by create next app'
};

export default function Layout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
